substitutions:
  _ENV: "staging"
  _SERVICE_NAME: "demo-service"
  _REGION: "europe-west2"



steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
     - '-c'  
     - |
        echo "==== Accessing Custom Substitutions ===="
        DEPLOY_ENV="${_ENV}"
        SERVICE_NAME="${_SERVICE_NAME}"
        REGION="${_REGION}"      


  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== builtin variables ==="
        echo "PROJECT_ID: $PROJECT_ID"
        echo "REPO_NAME: $REPO_NAME"
        echo "BRANCH_NAME: $BRANCH_NAME"
        echo "SHORT_SHA: $SHORT_SHA"
        echo "TRIGGER_NAME: ${TRIGGER_NAME}"
options:
  logging: CLOUD_LOGGING_ONLY