substitutions:
  _ENV: "staging"
  _SERVICE_NAME: "demo-service"
  _REGION: "europe-west2"
 
steps:
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir -p output
        echo "==== Accessing Custom Substitutions ====" > output/substitutions.txt
        echo "DEPLOY_ENV=${_ENV}"        >> output/substitutions.txt
        echo "SERVICE_NAME=${_SERVICE_NAME}" >> output/substitutions.txt
        echo "REGION=${_REGION}"         >> output/substitutions.txt

artifacts:
  objects:
    location: 'gs:// gcp-devops-cert-bucket/artifacts/artifacts-demo/'
    paths:
      - 'output/substitutions.txt'

options:
  logging: CLOUD_LOGGING_ONLY